apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: devops-demo
        image: ramya1998ram/devops-demo:39e74d61183b11f7a39078b2be44e0b0f335bb0f
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
