apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: devops-demo
        image: ramya1998ram/devops-demo:a089d26613424b0af5679e4eafa3053d22ad46bb
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
