apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: devops-demo
        image: ramya1998ram/devops-demo:868cdf98e5d5c4b2eaed074220d3666956e3e5c6
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
