name: Minikube CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ramya1998ram/devops-demo

jobs:
  deploy:
    runs-on: self-hosted   # your Mac runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .

      # 2. Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}

      # 3. Update deployment.yaml automatically
      - name: Update Kubernetes manifest
        run: |
          sed -i '' 's|image: .*|image: '"$IMAGE_NAME:${{ github.sha }}"'|g' k8s/deployment.yaml

      # 4. Apply to Minikube
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment devops-demo-deployment